"""任务目标与静态场地特征感知的公共契约。"""

from rescue_vision.perception.backend import FakeInferenceBackend, InferenceBackend
from rescue_vision.perception.detector import (
    RealtimeDetectionResult,
    StaleObservationError,
    TargetPoseDetector,
)
from rescue_vision.perception.field_feature_detector import FieldFeatureDetector
from rescue_vision.perception.field_feature_types import (
    BoundaryFeatureKind,
    BoundaryFeatureObservation,
    CenterCrossObservation,
    FieldFeatureConfig,
    FieldFeatureDetectionResult,
    FieldFeatureQuality,
    LineSegmentObservation,
    RealtimeFieldFeatureResult,
    SafeZoneColor,
    SafeZoneHalfObservation,
    SafeZoneObservation,
    SafeZoneSide,
    StartZoneObservation,
)
from rescue_vision.perception.target_ground_geometry import (
    BoxTargetGeometry,
    GroundGeometryMethod,
    GroundGeometryQuality,
    RealtimeTargetGroundGeometryResult,
    RegularTetrahedronTargetGeometry,
    StaleGroundGeometryError,
    TargetGeometry,
    TargetGeometryShape,
    TargetGroundGeometry,
    TargetGroundGeometryConfig,
    TargetGroundGeometryEstimator,
)
from rescue_vision.perception.visualization import (
    PerceptionFrameRenderer,
    render_target_observations,
)
from rescue_vision.perception.types import (
    COLOR_TARGET_CLASSES,
    ClassProbabilities,
    ColorSegmentationStatus,
    HsvColorClassifierConfig,
    HsvRange,
    ModelDetection,
    ObservationQuality,
    RoiColorSegmentation,
    TargetClass,
    TargetObservation,
    UndistortedBoundingBox,
)

__all__ = [
    "COLOR_TARGET_CLASSES",
    "BoundaryFeatureKind",
    "BoundaryFeatureObservation",
    "BoxTargetGeometry",
    "CenterCrossObservation",
    "ClassProbabilities",
    "ColorSegmentationStatus",
    "FakeInferenceBackend",
    "FieldFeatureConfig",
    "FieldFeatureDetectionResult",
    "FieldFeatureDetector",
    "FieldFeatureQuality",
    "HsvColorClassifierConfig",
    "HsvRange",
    "InferenceBackend",
    "GroundGeometryMethod",
    "GroundGeometryQuality",
    "LineSegmentObservation",
    "RealtimeFieldFeatureResult",
    "RealtimeTargetGroundGeometryResult",
    "RegularTetrahedronTargetGeometry",
    "ModelDetection",
    "ObservationQuality",
    "RealtimeDetectionResult",
    "RoiColorSegmentation",
    "SafeZoneColor",
    "SafeZoneHalfObservation",
    "SafeZoneObservation",
    "SafeZoneSide",
    "StaleObservationError",
    "StaleGroundGeometryError",
    "TargetClass",
    "TargetGeometry",
    "TargetGeometryShape",
    "TargetGroundGeometry",
    "TargetGroundGeometryConfig",
    "TargetGroundGeometryEstimator",
    "TargetObservation",
    "TargetPoseDetector",
    "StartZoneObservation",
    "UndistortedBoundingBox",
    "PerceptionFrameRenderer",
    "render_target_observations",
]
