"""Rescue Car 底盘/夹爪控制、协议适配与远程调试执行。"""

from rescue_vision.motion.controller import (
    MotionController,
    MotionControlTimingError,
    MotionSynchronizationError,
    MotionLimits,
)
from rescue_vision.motion.protocol import (
    CarCommandReply,
    CarStopReason,
    CarSystemStatus,
    CommandResult,
    ControllerProtocolError,
    MessageType,
    OdometryImu,
    ParsedCarMessage,
    SensorFlags,
    SystemFlags,
    crc16_ccitt_false,
    encode_emergency_stop_command,
    encode_gripper_command,
    encode_soft_brake_command,
    encode_state_query_command,
    encode_wheel_speed_command,
    pack_protocol_frame,
    parse_controller_frame,
)
from rescue_vision.motion.remote_control import (
    ExecutedRemoteGripper,
    ExecutedRemoteMotion,
    GripperCalibration,
    RemoteGripperError,
    RemoteGripperExecutor,
    RemoteGripperResult,
    RemoteMotionError,
    RemoteMotionExecutor,
    RemoteMotionResult,
    run_remote_motion,
)
from rescue_vision.motion.recording import (
    MANUAL_MOTION_LOG_FILENAME,
    MANUAL_MOTION_STREAM_NAME,
    ManualMotionLogWriter,
    inspect_manual_motion_log,
)

__all__ = [
    "CarCommandReply",
    "CarStopReason",
    "CarSystemStatus",
    "CommandResult",
    "ControllerProtocolError",
    "ExecutedRemoteGripper",
    "ExecutedRemoteMotion",
    "GripperCalibration",
    "MotionController",
    "MotionControlTimingError",
    "MotionSynchronizationError",
    "MotionLimits",
    "MANUAL_MOTION_LOG_FILENAME",
    "MANUAL_MOTION_STREAM_NAME",
    "ManualMotionLogWriter",
    "MessageType",
    "OdometryImu",
    "ParsedCarMessage",
    "RemoteGripperError",
    "RemoteGripperExecutor",
    "RemoteGripperResult",
    "RemoteMotionError",
    "RemoteMotionExecutor",
    "RemoteMotionResult",
    "SensorFlags",
    "SystemFlags",
    "crc16_ccitt_false",
    "encode_emergency_stop_command",
    "encode_gripper_command",
    "encode_soft_brake_command",
    "encode_state_query_command",
    "encode_wheel_speed_command",
    "pack_protocol_frame",
    "parse_controller_frame",
    "inspect_manual_motion_log",
    "run_remote_motion",
]
